### ISSUE TITLE
Fix for the cut of .jpg.json

### ISSUE THREAD

**Issue by BudhirajaMadhav** [m1rkwood/google-photos-takeout-scripts#3]
Since the double extension for larger named files get cut from .jpg.json to .json 
It can be fixed with the following script

`find . -type f ! -name "*.json" ! -name "*.json.*" -exec sh -c 'for file do extension="${file##*.}"; json_file="${file%.*}.json"; json_rename="${file%.*}.${extension}.json"; if [ ! -e "${json_rename}" -a -e "${json_file}" ]; then echo "Renaming ${json_file} to ${json_rename}"; mv "${json_file}" "${json_rename}"; else echo "Skipping ${file} - ${json_rename} already exists or no JSON file found"; fi; done' sh {} +
`

**Comment by m1rkwood** [comment]
Hello! Thanks a lot for your contribution, that's indeed something I solved manually when I did the export.
I've added the script to the documentation! Thank you :)
